spring:
  datasource:
    url: jdbc:postgresql://dpg-d0lnrbd6ubrc73c90h50-a.oregon-postgres.render.com:5432/surveydb_64zl #${spring.datasource.url}
    username: harbaoui #${spring.datasource.username}
    password: r5sfSsAlxAG7YahqgWHetyqg86AZOlS2 #${spring.datasource.password}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

web:
  cors:
    allowed-origins: '*'
    allowed-methods: GET,POST,PUT,DELETE
    allowed-headers: '*'